### PR TITLE
some fix for handling configuration change and recycling

### PR DESCRIPTION
**Pull request by pan-wang**
fixing issue #525 and #537

### CODE REVIEW

**Comment by jkotalik** [comment]
How much did you verify this @pan-wang . We should confirm that application stop does trigger on application stop and configuration change.

**Comment by shirhatti** [comment]
Does this address some prior issues around this space?
- https://github.com/aspnet/AspNetCoreModule/issues/105
- https://github.com/aspnet/AspNetCoreModule/issues/247

**Comment by pan-wang** [comment]
this pr address https://github.com/aspnet/IISIntegration/issues/525 and https://github.com/aspnet/IISIntegration/issues/537. We do have tests covering those scenarios.  @jhkimnew can confirm.

@shirhatti I will try repro that two issues. The code got changed significantly. they may not reproduce anymore.

**Comment by jkotalik** [comment]
@pan-wang are you asking @jhkimnew to verify these changes?

**Comment by shirhatti** [comment]
@pan-wang Given that my question went unanswered, I'm assuming we never tried to repro these issues 😄 
- https://github.com/aspnet/AspNetCoreModule/issues/105
- https://github.com/aspnet/AspNetCoreModule/issues/247

@jhkimnew Can you please give it a try and close the respective issue if they no longer repro?

**Comment by pan-wang** [comment]
@shirhatti, I did try repro it but could not. The app-offline and handling web.config change were changed in the new code. This issue should be not reproducible.

**Pull request merged**
