### PR TITLE
Add test for log file with unicode

### PR DESCRIPTION
**Pull request by jkotalik**
For #692

### CODE REVIEW

**Comment by jkotalik** [comment]
Having `/??????????.htm` in the std output is expected as the encoding is not set to unicode/utf8. Decided to add a test for the log file being in unicode.

**Comment by pakrym** [comment]
This is not what bug was talking about

**Comment by pakrym** [comment]
Change the existing test to use unicode name. Not much point in having both.

**Comment by jkotalik** [comment]
Closing as redundant/won't fix.

**Pull request closed without merging**
