### PR TITLE
Fix test server issues.

### PR DESCRIPTION
**Pull request by jkotalik**
Seems like delaying in dispose for a bit stops issues in hostable web core. Ran 100 times locally without failures. Unfortunate 😢

### CODE REVIEW

**Comment by jkotalik** [comment]
Closing and reopening for more coverage.

**Comment by jkotalik** [comment]
Test failure: https://github.com/aspnet/IISIntegration/issues/1494

**Comment by pakrym** [comment]
Does it work without sleep?

**Comment by jkotalik** [comment]
From what I can tell no. I can try reducing the sleep timeout, but I couldn’t find any other combination that worked (without a different approach).

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pakrym** [comment]
Rerun PR multiple times please.

**Comment by pakrym** [comment]
Add a comment

**Pull request merged**
