### PR TITLE
Create a separate sln for V1

### PR DESCRIPTION
**Pull request by jkotalik**
Part of cleanup for #899. Searching through code with ANCMV1 and V2 in it is painful. This will make searching easier and keep V1 and V2 separate.

### CODE REVIEW

**Comment by pakrym** [comment]
I though about this recently and think we need sln file without V2 (like MVC has MVCNoFun ) but the main one should have everything in it.

**Comment by jkotalik** [comment]
How does Mvc make it so build.cmd only invokes build on the main solution?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pakrym** [comment]
Isn't that what korebuild is doing by default?

**Comment by jkotalik** [comment]
@pakrym I updated this to create a .NoV1 sln.

**Comment by pakrym** [comment]
What's our guidance on updating this? Make changes to the main one then remove a project and overwrite NoV1?

**Comment by jkotalik** [comment]
Yeah I guess that's the best move.

**Comment by pakrym** [comment]
Can we add a `dotnet sln` based script to regenerate this?

**Comment by jkotalik** [comment]
@pranavkm does MVC have a script to update the NoFun sln? From what I can tell, there isn't a way.

**Comment by pranavkm** [comment]
Nope, it's manually curated.

**Pull request merged**
