### PR TITLE
Remove x-fowarded-for and x-forwarded-proto.

### PR DESCRIPTION
**Pull request by Tratcher**
@muratg @blowdart @davidfowl 
We're going to consolidate this logic over in https://github.com/aspnet/BasicMiddleware/blob/dev/src/Microsoft.AspNet.HttpOverrides/OverrideHeaderMiddleware.cs and make it more configurable.

### CODE REVIEW

**Comment by davidfowl** [comment]
What?

**Comment by davidfowl** [comment]
@Tratcher Do you have a bug on the Templates repository to add the forwarding middleware?

**Comment by Tratcher** [comment]
https://github.com/aspnet/Templates/issues/343

**Comment by muratg** [comment]
:shipit:

**Comment by GuardRex** [comment]
https://tools.ietf.org/html/rfc7239 ... You took a look at this earlier, but nothing came back "yeah" or "nay" ... just curious what the outcome of the internal discussion was.

**Comment by Tratcher** [comment]
@GuardRex HttpPlatformHandler work will pick up again in Jan.

**Pull request merged**
