### PR TITLE
Guard OnAsyncCompletion from completing request before OnExecuteRequestHandler exits

### PR DESCRIPTION
**Pull request by pakrym**
If this happens request module would get freed causing all kinds of unexpected consequences.

### CODE REVIEW

**Comment by pakrym** [comment]
Windows Debug x64 Build failure would get fixed by https://github.com/aspnet/IISIntegration/pull/1484

**Comment by pakrym** [comment]
Windows Release x64 Build is WriterThrowsCancelledException failing again :(

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Comment by jkotalik** [comment]
> Windows Release x64 Build is WriterThrowsCancelledException failing again :(

Revert 😢 ?

**Comment by pakrym** [comment]
@dotnet-bot test Windows Debug x64 Build

**Pull request merged**
