### PR TITLE
Add compression pass through tests

### PR DESCRIPTION
**Pull request by pakrym**
@Tratcher, do you think is this a valid test for https://github.com/aspnet/IISIntegration/issues/1523 ?

### CODE REVIEW

**Comment by Tratcher** [comment]
No 
1. Pull in the actual response compression middleware (the repo layering allows it).
1. Disable response compression in IIS
1. Disable response decompression on the client, but set the Accept-encoding header manually
1. Set a compressible content-type (text/plain), write data
1. Read the response. Make sure the Content-Encoding header is set. Make sure the content is compressed.

**Comment by pakrym** [comment]
> Also need to disable compression in IIS.

Disabled by default in deployers.

**Comment by pakrym** [comment]
@Tratcher  ping

**Comment by pakrym** [comment]
Failures are known and are being addressed

**Pull request merged**
