### PR TITLE
Test with the bin deployed aspnetcore.dll

### PR DESCRIPTION
**Pull request by Tratcher**
#292 
Depends on https://github.com/aspnet/Hosting/pull/879
@JunTaoLuo @pranavkm 
/cc: @shirhatti @pan-wang

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]
looks good to me

**Comment by Tratcher** [comment]
@muratg, mind if we make these test changes for 1.1? It gives us real coverage for ancm.

**Comment by shirhatti** [comment]
Did we chose to run against 64-bit IIS Express (and hence test only 64-bit version of ANCM) as a conscious decision or is 32-bit IIS Express just an omission?

**Comment by Tratcher** [comment]
That's an existing gap in our coverage. The current approach would test 32bit on 32bit OSs, but we don't run any of those. VS uses 32bit express, correct? Maybe we need a variant for it.

**Comment by Tratcher** [comment]
https://github.com/aspnet/Hosting/issues/880

**Comment by muratg** [comment]
@Tratcher can you start a thread for approval?

**Comment by Tratcher** [comment]
Moving to dev for now.

**Pull request closed without merging**
