### PR TITLE
Default to checking program files if dotnet on path doesn't match bitness of worker process.

### PR DESCRIPTION
**Pull request by jkotalik**
For #519. We could also check further on the path too, but I believe this is the approach we wanted to take.

### CODE REVIEW

**Comment by Tratcher** [comment]
Does this work both ways? E.g. 32->64 and 64->32?

Also, I remembered why we didn't do this to start with, it breaks dev environments where the dotnet we want isn't in program files, it's in the user profile. What was that you said about continuing to search down the user's path? Can SearchPath be called again to keep looking?

**Comment by jkotalik** [comment]
@Tratcher can you clarify the scenario for going both ways? Like switching between 32 and 64 bit worker processes?

For IISExpress, this will work in dev environments because we still look on the system path for dotnet first (where we expect people to add C:\Users\USER_PROFILE\.dotnet\x64 to the path). However it won't work in the IIS scenario as it won't have access to the user profile. This could cause issues running full IIS tests on our CI machines.

Instead of looking in program files, we could instead look further on the path, where other dotnet locations would be specified. For example, my path is C:\Users\USER_PROFILE\.dotnet\x64;C:\Program Files (x86)\dotnet;C:\Program Files\dotnet. SearchPath would return the first C:\Users\USER_PROFILE\.dotnet\x64, however I would like to get the x86 location as it matches the bitness of my process. I'm going to investigate whether we can continue calling SearchPath to look further on the path. My guess is no, but I will confirm.

**Comment by jkotalik** [comment]
Closing in favor of #541.

**Comment by jhkimnew** [comment]
@jkotalik Can you list the required test scenarios after this code update?

**Comment by jkotalik** [comment]
Yeah I'll let you know once #541 is in.

**Pull request closed without merging**
