### PR TITLE
Avoid merging with anonymous users.

### PR DESCRIPTION
**Pull request by Tratcher**
https://github.com/aspnet/Common/issues/85
@blowdart @muratg 
This avoids the issue most of the time. We'll still want to make principal merging smarter at some point.

### CODE REVIEW

**Comment by muratg** [comment]
:shipit:

**Comment by mrsheepuk** [comment]
Hi guys - quick question on this - I'm using the code below to set up some policies to authorise users against membership in certain AD groups - I'm finding that it's only working if I use SIDs as the group names when hosting in IIS - Kestrel (it works perfectly using weblistener outside IIS) on RC1-Update1 - am I right in thinking this change will address the problem I'm seeing, such that this should work against group names correctly in RC2? 

Is using the SIDs a sensible, safe workaround until RC2 is released?

Thanks!!

```
var viewerGroups = Configuration.GetSection("InternalGroups:Viewer").Value.Split(',');
var adminGroups = Configuration.GetSection("InternalGroups:Admin").Value.Split(',');
var namedGroups = Configuration.GetSection("InternalGroups:Named").Value.Split(',');
services.AddAuthorization(auth =>
{
    auth.AddPolicy("read", policy =>
    {
        policy.RequireRole(viewerGroups);
    });
    auth.AddPolicy("admin", policy =>
    {
        policy.RequireRole(adminGroups);
    });
    auth.AddPolicy("named", policy =>
    {
        policy.RequireRole(namedGroups);
    });
});
```

**Comment by Tratcher** [comment]
Yes this change will probably address your scenario. In the meantime using the sids should be ok.

**Comment by mrsheepuk** [comment]
Thanks @Tratcher - I'll check using names again once the next RC comes out.

**Pull request merged**
