### PR TITLE
Rename UseIIS() to UseIISIntegration()

### PR DESCRIPTION
**Pull request by Tratcher**
#121 @Eilon @DamianEdwards @JunTaoLuo @muratg

### CODE REVIEW

**Comment by muratg** [comment]
:shipit:  

Any other repos need to do this?

**Comment by Tratcher** [comment]
ServerTests and MusicStore. I'm going to merge this before johns changes so he can do all the other samples.

**Comment by JunTaoLuo** [comment]
@muratg Yes, all the samples.

**Comment by rustd** [comment]
@Tratcher please send a PR to the templates repo as well.

**Pull request closed without merging**
