### PR TITLE
Add back AutomaticAuthentication for opt-out.

### PR DESCRIPTION
**Pull request by Tratcher**
#390 @PinpointTownes
Reverts an un-needed breaking change.

### CODE REVIEW

**Comment by PinpointTownes** [comment]
@Tratcher did you chat with @davidfowl? We discussed this pain point on Slack and I suggested another approach, that would potentially make things look way better.

**Comment by PinpointTownes** [comment]
While you're fixing that, you may also want to fix https://github.com/aspnet/IISIntegration/issues/391, which is also a regression.

**Comment by Tratcher** [comment]
Offline: This is the lowest risk change we can make at the moment.

**Comment by PinpointTownes** [comment]
Less than ideal but better than nothing, I suppose. What about the other issue?

**Comment by Tratcher** [comment]
Yes I expect we'll fix #391, but I don't know how soon.

**Pull request merged**
