### PR TITLE
Fix Jenkins even more

### PR DESCRIPTION
**Pull request by pakrym**
I was blinded by the happiness of seeing green builds and didn't check the logs.

### CODE REVIEW

**Comment by jkotalik** [comment]
Why did you change build.cmd to build.ps1?

**Comment by pakrym** [comment]
Build cmd calls into ps1 and we are running inside powershell anyway.

**Comment by pakrym** [comment]
This fixes test running, but there is still flakiness.

Interestingly it fails the same way our win7 tests do:
```
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: Application ready at URL: http://localhost:54999/
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests Debug: Method: GET, RequestUri: 'http://localhost:54999/HelloWorld', Version: 2.0, Content: <null>, Headers:
   |                                                                                                      {
   |                                                                                                      }
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: IncrementMessages called
   | [2018-05-25T22:55:52] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request started: "GET" http://localhost:54999/HelloWorld
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr: It was not possible to find any compatible framework version
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr: The specified framework 'Microsoft.NETCore.App', version '2.2.0-preview1-26509-06' was not found.
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - Check application dependencies and target a framework version installed at:
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       C:\Program Files\IIS Express\
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - Installing .NET Core prerequisites might help resolve this problem:
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:   - The .NET Core framework and SDK can be installed from:
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Warning: iisexpress stderr:       https://aka.ms/dotnet-download
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IntegrationTesting.IISExpressDeployer Information: iisexpress stdout: Request ended: http://localhost:54999/HelloWorld with HTTP status 500.0
   | [2018-05-25T22:55:53] Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests.StartupTests Warning: StatusCode: 500, ReasonPhrase: 'Internal Server Error', Version: 1.1, Content: System.Net.Http.HttpConnection+HttpConnectionResponseContent, Headers:
   |                                                                                                        {
   |                                                                                                          Cache-Control: private
   |                                                                                                          Server: Microsoft-IIS/10.0
   |                                                                                                          X-SourceFiles: =?UTF-8?B?QzpcVXNlcnNccnVubmVyXEFwcERhdGFcTG9jYWxcVGVtcFxkOTA5MmExNS0yMzhjLTQ4OTktYjY3MS01MmI1ZDRkMGE5YjdcSGVsbG9Xb3JsZA==?=
   |                                                                                                          X-Powered-By: ASP.NET
   |                                                                                                          Date: Fri, 25 May 2018 22:55:53 GMT
   |                                                                                                          Content-Type: text/html; charset=utf-8
   |                                                                                                          Content-Length: 5821
   |                                                                                                        }
```

**Comment by jkotalik** [comment]
Are the jenkins agents accessible for debugging/remoting on?

**Comment by jkotalik** [comment]
Error is app is failing to start/exec: E_APPLICATION_ACTIVATION_EXEC_FAILURE. Interesting failure.

**Comment by pakrym** [comment]
It seems like we are passing wrong exe name, it tries to find frameworks in `C:\Program Files\IIS Express\`

**Comment by jkotalik** [comment]
how could that cause a race though?

**Comment by Tratcher** [comment]
Doesn't look like a race on Win7, the same tests always fail.

**Comment by pakrym** [comment]
Filed https://github.com/aspnet/IISIntegration/issues/875

**Pull request merged**
