### PR TITLE
disable two failed tests temporarily

### PR DESCRIPTION
**Pull request by troydai**
issue: #187 

buddy build note: these two tests fail on Windows 2008 platform only for the moment. disable during the investigation.

### CODE REVIEW

**Comment by Tratcher** [comment]
:-1: This is not a scenario we can ignore. Work with @JunTaoLuo to resolve this today.

**Comment by troydai** [comment]
/cc @Eilon 

Both @Tratcher and @JunTaoLuo are against the idea to disable this test. @JunTaoLuo is actively investigate this one for now. 

I'll hold on till later today to see if these two failures are the last block issues toward a coherence-signed.

**Comment by Eilon** [comment]
Disabling is fine temporarily. Getting builds out is critical. We just need to make fixing the tests/product a super high priority. But we shouldn't block everything due to it.

**Comment by Eilon** [comment]
:shipit:

**Pull request merged**
