### PR TITLE
Disconnect the disconnect handler when request processing ends 

### PR DESCRIPTION
**Pull request by pakrym**
Main changes from the previous try: Initialize disconnect handler before calling OnProcessRequest to avoid races with OnAsyncCompletion that can happen even before ProcessRequest  ends.

Additional changes to SetupTestEnvironment allow us to capture w3wp dumps on VSTS by removing vsjit that was kicking in and preventing dumps from being created.

### CODE REVIEW

**Comment by jkotalik** [comment]
@natemcmaster automated deps update is causing sign tool failures again: https://github.com/aspnet/IISIntegration/commit/b2e55456c705bbf57366ee8fcb88b9c52e4f96a5. Do we need to revert it again? What is the underlying issue here?

**Comment by natemcmaster** [comment]
> 2018-10-08T16:15:58.8656500Z D:\a\1\s\.dotnet\x64\sdk\2.2.100-preview2-009404\NuGet.targets(114,5): error : Failed to download package 'Newtonsoft.Json.9.0.1' from 'https://api.nuget.org/v3-flatcontainer/newtonsoft.json/9.0.1/newtonsoft.json.9.0.1.nupkg'. [D:\a\1\s\IISIntegration.sln]
2018-10-08T16:15:58.8657426Z D:\a\1\s\.dotnet\x64\sdk\2.2.100-preview2-009404\NuGet.targets(114,5): error : Response status code does not indicate success: 502 (Bad Gateway). [D:\a\1\s\IISIntegration.sln]

Seems like VSTS failed with a network error.

> signtool : error : D:\j\workspace\windows-Confi---dfc477d1\artifacts\build\Microsoft.AspNetCore.Server.IISIntegration.2.2.0-preview3-906.nupkg has part lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll which does not match the content in the binaries directory [C:\Users\runner\.dotnet\buildtools\korebuild\2.2.0-preview2-20181004.6\KoreBuild.proj]
09:11:13 signtool : error : D:\j\workspace\windows-Confi---dfc477d1\artifacts\build\Microsoft.AspNetCore.Server.IISIntegration.2.2.0-preview3-906.symbols.nupkg has part lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll which does not match the content in the binaries directory [C:\Users\runner\.dotnet\buildtools\korebuild\2.2.0-preview2-20181004.6\KoreBuild.proj]

I've looked into errors like this on other repos. It's usually caused by an incorrect project config that causes double writes. The EF Core team was complaining about the same error, so I've opened this bug to track investigation: https://github.com/aspnet/BuildTools/issues/787

**Comment by pakrym** [comment]
I think we need to revert deps to be able to make progress while the investigation is happening.

**Comment by natemcmaster** [comment]
> I think we need to revert deps to be able to make progress while the investigation is happening.

Feel free to do that.

**Comment by pakrym** [comment]
@dotnet-bot test this please

**Pull request merged**
