### PR TITLE
publish-iis default values, Azure

### PR DESCRIPTION
**Pull request by moozzyk**

### CODE REVIEW

**Comment by Tratcher** [comment]
@davidfowl, you did all of this last time.

**Comment by moozzyk** [comment]
Yeah - I mostly moved it from [here](https://github.com/aspnet/dnx/blob/819a6e603b0f43ef1a9da539ecc8ecc29a16bdbc/src/Microsoft.Dnx.Tooling/Publish/PublishProject.cs#L568-L574)

**Comment by moozzyk** [comment]
@davidfowl :watch:

**Comment by muratg** [comment]
:shipit:

**Pull request closed without merging**
