### PR TITLE
Delete Microsoft.AspNetCore.Server.IISIntegration.Tools

### PR DESCRIPTION
**Pull request by natemcmaster**
There will be no preview3 release of this package. The functionality of this tool will be ported to an MSBuild task. cref #258 

cc @muratg @pranavkm

### CODE REVIEW

**Comment by natemcmaster** [comment]
⌚ on downgrading tests to preview2

**Comment by Tratcher** [comment]
Needs to downgrade ServerTests, MusicStore, Entropy, etc..

**Comment by natemcmaster** [comment]
cc @moozzyk

**Comment by moozzyk** [comment]
:ship::it:

**Comment by GuardRex** [comment]
#### Farewell `Microsoft.AspNetCore.Server.IISIntegration.Tools`

Your amazing life with us will always be remembered. You were always there for us, always working to make our lives easier. The server gods may have recalled you from us, but know that derivatives and extensions of your codebase will live on with us in your clones. Let us not dwell on the pain of your departure for long but instead come to rejoice in the glory of your time with us. `publish-iis`, I raise a toast to you and wish you a fond farewell. :beer:

On a serious note tho ... Well done @moozzyk! Well done, Sir. `publish-iis` was a wonderful piece of engineering and a great example for other tools of its ilk. If you ever get to missing your dearly departed, please feel free to try [GuardRex.AspNetCore.Server.IISIntegration.Tools](https://github.com/GuardRex/GuardRex.AspNetCore.Server.IISIntegration.Tools) ... a not too good clone that hopefully won't fry your motherboard. :smile:

**Comment by moozzyk** [comment]
Thanks @GuardRex!

**Pull request merged**
