### PR TITLE
Update branding for 2.1.5

### PR DESCRIPTION
**Pull request by natemcmaster**
Changes the branding for the 2.1.5 release because this repo is taking patches

### CODE REVIEW

**Comment by natemcmaster** [comment]
FYI @shirhatti @pakrym @jkotalik - when this merges, you are free to add other approved 2.1.5 work to release/2.1.

**Comment by jkotalik** [comment]
Actually, if there are no code changes in Microsoft.AspNetCore.Server.IISIntegration, do we need to update the version? All changes are in ANCM.

**Comment by natemcmaster** [comment]
Do you use the version.props file to set versions in aspnetcoremodulev1.dll?

**Comment by jkotalik** [comment]
We use version.props, but other versions: https://github.com/aspnet/IISIntegration/pull/1320/files#diff-2a92b4d7f8df251ffd3a0aa63e97aad5L11

**Comment by natemcmaster** [comment]
I see. My patching scripts didn't account for these variables. Presumably these should change too, right?

**Comment by jkotalik** [comment]
They will: https://github.com/aspnet/IISIntegration/pull/1286

**Comment by natemcmaster** [comment]
I see.

Generally, our philosophy has been "if one thing in a repo patches, everything in the repo patches." Our current build system is not flexible enough to partially re-build a repo. Even though patching the managed bits is unnecessary, but at the Universe layer all we have is an on/off switch. See https://github.com/aspnet/Universe/pull/1328/files#diff-98c23780ba4fa4d6a335ead2dc489fe0

**Comment by jkotalik** [comment]
> if one thing in a repo patches, everything in the repo patches

Didn't realize that was the policy; I assumed versions only increase if an assembly or one of the assembly's dependencies change, not at a repo level.

**Comment by jkotalik** [comment]
So I guess it's fine to increase the version. I'll modify the other PR to use the `VerisonPrefix` value.

**Comment by jkotalik** [comment]
@natemcmaster can we merge this so I can finalize all 2.1.5 work?

**Comment by natemcmaster** [comment]
Not yet. The release/2.1 branch isn't open yet. I'll notify the team when they are.

**Pull request merged**
