### PR TITLE
adding general logging event for future use

### PR DESCRIPTION
**Pull request by pan-wang**

### CODE REVIEW

**Comment by jkotalik** [comment]
I'd say we add warning and error messages that are the same as the general message, for the sake of ease of use.

**Comment by pan-wang** [comment]
we only need event ID for general info, warning, and error event. The message is just a string input. why do we need different messages?

**Comment by jkotalik** [comment]
Every time we log, we do something like:

```cpp

        // Application got recycled. Log an event
        STACK_STRU(strEventMsg, 256);
        if (SUCCEEDED(strEventMsg.SafeSnwprintf(
            ASPNETCORE_EVENT_RECYCLE_CONFIGURATION_MSG,
            pszApplicationId)))
        {
            UTILITY::LogEvent(g_hEventLog,
                EVENTLOG_INFORMATION_TYPE,
                ASPNETCORE_EVENT_RECYCLE_CONFIGURATION,
                strEventMsg.QueryStr());
        }
```

It is nice to have the MSG and error types match even though they are the same thing.

**Comment by pan-wang** [comment]
it seems we don't need the msg at all. Just event ID is sufficient enough. The input to UTULITY::LogEvent is just a string. We don't need to duplicate the string, i.e., use strEventMsg. Current code, we uses strEventMsg because we put some parameters such as hr value and et al into the string which is not available for Generic one. Also Generic one does not support localization.

**Comment by jkotalik** [comment]
That's fine by me.

**Pull request merged**
