### PR TITLE
Bump test projects up to .NET 4.5.2

### PR DESCRIPTION
**Pull request by dougbu**
- aspnet/Testing#248
- xUnit no longer supports .NET 4.5.1
- build tests for desktop .NET only on Windows
  - except Microsoft.AspNetCore.Server.IISIntegration.FunctionalTests; will skip that another way (later)

Also fix line endings in project files; unable to proceeed otherwise

### CODE REVIEW

**Comment by dougbu** [comment]
Would like a few eyes on this one because the line endings make things difficult to see and we don't have AppVeyor or Travis coverage.

**Comment by Tratcher** [comment]
What messed up the line endings? Blame?

**Comment by dougbu** [comment]
@natemcmaster's .csproj migration script. I blame `node` of course.

**Comment by dougbu** [comment]
But, `git` shows differences as soon as you clone this repo on Windows ☹️

**Comment by dougbu** [comment]
FYI I just checked and `?w=1` gets rid of the line ending fixup in the /files view of this PR.

**Comment by natemcmaster** [comment]
@dougbu these line ending changes shouldn't have been caused by my migration scripts. What is your version of Git.exe and your line-ending settings? 
`git --version`
`git config --global core.autocrlf`

**Comment by dougbu** [comment]
Why not just fix the line endings?

In any case,
```
> git --version
git version 2.9.0.windows.1
> git config core.autocrlf # can be overridden at any config level so --global may hide real value
true
```

**Comment by natemcmaster** [comment]
The reason I asked is that you seem to be the only one hitting issues with line endings. But it seems your settings are fine so go ahead and commit it.

**Comment by Tratcher** [comment]
@dougbu I pulled this repo and the line endings are fine. However, I also pulled your branch and the line endings are fine there too. You just broke Github?

**Comment by dougbu** [comment]
No idea but this has only happened with a couple of repos and a few files in each. In any case, I'll push this and hope the problem doesn't recur anywhere.

**Comment by dougbu** [comment]
8ae481c

**Pull request merged**
